### ISSUE TITLE
`is_allowed` output type

### ISSUE THREAD

**Issue by lhoestq** [Spawning-Inc/datadiligence#1]
Hi ! The example in the README shows
```python
>>> import datadiligence as dd
>>> urls = ["https://www.example.com/art-123456789.jpg", "https://www.example.com/art-987654321.jpg"]
>>> dd.is_allowed(urls=urls)
["https://www.example.com/art-123456789.jpg"]
```

However
1. it's usually expected to return booleans when a function name starts with `is_`
2. `is_allowed` returns a bool if the `response=` is passed

Because of this I think `is_allowed` should return a list of booleans instead of a list of URLs in the example.

To keep allowed URLs we can imagine `allowed_urls = filter_allowed(urls=urls)` instead

cc @Padge91

**Comment by Padge91** [comment]
@lhoestq I completely agree. We have some loose stubs for this behavior already with our `BulkRule` class, it just didn't materialize into a consistent method. This should be straightforward to implement. Thank you!

**Comment by Padge91** [comment]
@lhoestq I've created a pull request [here](https://github.com/Spawning-Inc/datadiligence/pull/2). This is what you had in mind, correct? No rush, at your convenience

**Comment by lhoestq** [comment]
It looks perfect, thanks !
